---
name: Release and publish package to clojars.org

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

jobs:
  release:
    uses: 'openvoxproject/shared-actions/.github/workflows/clojure_release.yml@main'
    secrets:
      github_pat: ${{ secrets.OPENVOXBOT_COMMIT_AND_PRS }}
      ssh_private_key: ${{ secrets.OPENVOXBOT_SSH_PRIVATE_KEY }}
      clojars_username: ${{ secrets.CLOJARS_USERNAME }}
      clojars_password: ${{ secrets.CLOJARS_PASSWORD }}
